# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Dimelo Mobile Messaging
description: Dimelo Mobile Messaging SDK for iOS
author:
  name: Renaud (Nel) Morvan
  email: nel@w3fu.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: date
paginate: 5
paginate_path: 'page:num'

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: true
